### ISSUE TITLE
Failed config

### ISSUE THREAD

**Issue by andyenns** [JuergenLeber/home-assistant-optolink#2]
Hi,
i'm getting en error when i try to install the code via ESPhome

INFO ESPHome 2024.12.4
INFO Reading configuration /config/esphome/optolink-heating.yaml...
Failed config

external_components: [source /config/esphome/optolink-heating.yaml:17]
  - source: 
      type: git
      url: https://github.com/JuergenLeber/esphome
      ref: dm9051
      
      [components] is an invalid option for [source]. Please check the indentation.
      components: 
        - ethernet
      
      [refresh] is an invalid option for [source]. Did you mean [ref]?
      refresh: 0s
  - source: 
      type: git
      url: https://github.com/JuergenLeber/esphome_vitoconnect

can you please help?
Thanks!

**Comment by JuergenLeber** [comment]
Oh, seems like the markdown destroyed some of the tab indentations. Will fix that in the readme. Until then just take this one:

`esphome:
  name: heating-optolink
  friendly_name: heating-optolink
  build_path: esp32
  platformio_options:
    upload_speed: 115200

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: latest
    platform_version: 6.5.0

external_components:
  - source:
      type: git
      url: https://github.com/JuergenLeber/esphome
      ref: dm9051
    components:
      - ethernet
    refresh: 0s
  - source: 
      type: git
      url: https://github.com/JuergenLeber/esphome_vitoconnect
      ref: master
    refresh: 0s
      
ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 8MHz  

logger:
  hardware_uart: UART0
  level: DEBUG

uart:
  - id: uart_vitoconnect
    rx_pin: GPIO05
    tx_pin: GPIO02
    baud_rate: 4800
    data_bits: 8
    parity: EVEN
    stop_bits: 2

vitoconnect:
  uart_id: uart_vitoconnect
  protocol: KW
  update_interval: 30s

sensor:
  - platform: vitoconnect
    name: "Außentemperatur"
    address: 0x0800
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Kesseltemperatur"
    address: 0x0802
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Speichertemperatur"
    address: 0x0804
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Rücklauftemperatur"
    address: 0x080A
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Vorlauftemperatur"
    address: 0x080C
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Vorlaufsolltemperatur"
    address: 0x2544
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Kesselsolltemperatur"
    address: 0x555A
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Brennerstarts"
    address: 0x088A
    length: 4
    unit_of_measurement: ""
  - platform: vitoconnect
    name: "Brennerbetriebsstunden Stufe 1"
    address: 0x08A7
    length: 4
    unit_of_measurement: "s"
    device_class: duration
  - platform: vitoconnect
    name: "Brennerbetriebsstunden Stufe 2"
    address: 0x08AB
    length: 4
    unit_of_measurement: "s"
    device_class: duration
  - platform: vitoconnect
    name: "Ölverbrauch"
    address: 0x7574
    length: 4
    unit_of_measurement: "l"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    device_class: volume
  - platform: vitoconnect
    name: "Betriebsart"
    address: 0x2301
    length: 1
  - platform: vitoconnect
    name: "Heizkennlinie Niveau"
    address: 0x2304
    length: 1
  - platform: vitoconnect
    name: "Heizkennlinie Neigung"
    address: 0x2305
    length: 1
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: vitoconnect
    name: "Raumtemperatur Soll"
    address: 0x2306
    length: 1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

binary_sensor:
  - platform: vitoconnect
    name: "Störung"
    address: 0x0883
  - platform: vitoconnect
    name: "Heizkreispumpe"
    address: 0x250A
  - platform: vitoconnect
    name: "Warmwasserfreigabe"
    address: 0x2508

api:
  encryption:
    key: "<KEY>"

ota:
  - platform: esphome
    password: "<PASSWORD>"`

**Comment by andyenns** [comment]
Thank you for the quick response. I tried it with the right indentations and now i get the following error:

INFO ESPHome 2024.12.4
INFO Reading configuration /config/esphome/optolink.yaml...
INFO Updating https://github.com/JuergenLeber/esphome@dm9051
INFO Updating https://github.com/JuergenLeber/esphome_vitoconnect@master
Failed config

esp32: [source /config/esphome/optolink.yaml:9]
  board: esp32-c3-devkitm-1
  variant: esp32c3
  
  ESP-IDF 5.1.5 not supported by platformio/espressif32.
  framework: 
    type: esp-idf
    version: latest
    platform_version: 6.5.0

Is there a specific version and platform_version i should use?

**Comment by JuergenLeber** [comment]
That one should work (at least works here with newest ESPHome):

```yaml
esphome:
  name: heating-optolink
  friendly_name: heating-optolink
  build_path: esp32
  platformio_options:
    upload_speed: 115200

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/JuergenLeber/esphome
      ref: dm9051
    components:
      - ethernet
    refresh: 0s
  - source: 
      type: git
      url: https://github.com/JuergenLeber/esphome_vitoconnect
      ref: master
    refresh: 0s
      
ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 8MHz  

logger:
  hardware_uart: UART0
  level: DEBUG

uart:
  - id: uart_vitoconnect
    rx_pin: GPIO05
    tx_pin: GPIO02
    baud_rate: 4800
    data_bits: 8
    parity: EVEN
    stop_bits: 2

vitoconnect:
  uart_id: uart_vitoconnect
  protocol: KW
  update_interval: 30s

sensor:
  - platform: vitoconnect
    name: "Außentemperatur"
    address: 0x0800
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Kesseltemperatur"
    address: 0x0802
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Speichertemperatur"
    address: 0x0804
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Rücklauftemperatur"
    address: 0x080A
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Vorlauftemperatur"
    address: 0x080C
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Vorlaufsolltemperatur"
    address: 0x2544
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Kesselsolltemperatur"
    address: 0x555A
    length: 2
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    device_class: temperature
  - platform: vitoconnect
    name: "Brennerstarts"
    address: 0x088A
    length: 4
    unit_of_measurement: ""
  - platform: vitoconnect
    name: "Brennerbetriebsstunden Stufe 1"
    address: 0x08A7
    length: 4
    unit_of_measurement: "s"
    device_class: duration
  - platform: vitoconnect
    name: "Brennerbetriebsstunden Stufe 2"
    address: 0x08AB
    length: 4
    unit_of_measurement: "s"
    device_class: duration
  - platform: vitoconnect
    name: "Ölverbrauch"
    address: 0x7574
    length: 4
    unit_of_measurement: "l"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    device_class: volume
  - platform: vitoconnect
    name: "Betriebsart"
    address: 0x2301
    length: 1
  - platform: vitoconnect
    name: "Heizkennlinie Niveau"
    address: 0x2304
    length: 1
  - platform: vitoconnect
    name: "Heizkennlinie Neigung"
    address: 0x2305
    length: 1
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: vitoconnect
    name: "Raumtemperatur Soll"
    address: 0x2306
    length: 1
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

binary_sensor:
  - platform: vitoconnect
    name: "Störung"
    address: 0x0883
  - platform: vitoconnect
    name: "Heizkreispumpe"
    address: 0x250A
  - platform: vitoconnect
    name: "Warmwasserfreigabe"
    address: 0x2508

api:
  encryption:
    key: "<KEY>"

ota:
  - platform: esphome
    password: "<PASSWORD>"
```
